### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by zozors** [zozors/protospace-37978#1]
https://protospace-37978.herokuapp.com/

**Comment by motomuun** [comment]
@zozors さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] **ログアウト状態のユーザーであっても、トップページ・プロトタイプ詳細ページ・ユーザー詳細ページ・ユーザー新規登録ページ・ログインページには遷移できること**
- [x] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること**
ログアウト状態では`ユーザー詳細ページ`に遷移出来ませんので、修正をお願いします。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by zozors** [comment]
確認ありがとうございます。
未ログイン時でもユーザー詳細画面へ遷移できるよう修正し直しました。
こちらご確認宜しくお願いいたします。

**Comment by shodai-ito** [comment]
@zozors さん、再度ご提出いただきありがとうございます‼︎
動作の確認をしたところ、前回の指摘点について修正が確認できませんでした。
マージやデプロイ忘れの可能性もございます。
引き続き、上記指摘内容のご確認をお願い致します！

修正が完了しましたら、再度以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by zozors** [comment]
すみません、
git push heroku masterが未完了となっていました。
再度ご確認宜しくお願いいたします。

**Comment by snkw-works** [comment]
@zozors さん、再度ご提出いただきありがとうございます‼︎
修正が確認でき、正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
